package: api
output-file: internal/interfaces/api/generated.go
additional-imports:
  - alias: "api"
    package: "github.com/tomotakashimizu/devin-sandbox/todo-app/internal/interfaces/api"
generate:
  models: true
  server: true
  spec: true
